# Release CI
-
  branches:
    only:
      - master
  version: 0.2.0.0
  os: Visual Studio 2015
  configuration: Release
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    COVERALLS_REPO_TOKEN:
      secure: pJSh3uNVX95c4AMMnIWH6fy6EX8nywcfbgi2WqbuwYaWS6JQMHy6WFX0foQM4iHl
  before_build:
  - cmd: nuget restore src\Crankshaft.sln
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    project: src\Crankshaft.sln
    verbosity: minimal
  test_script:
  - cmd: >-
      src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe -targetargs:"src\En.Gen.Crankshaft.Tests\bin\release\Crankshaft.Tests.dll -noshadow -appveyor" -filter:"+[Crankshaft*]* -[*.Tests]*" -output:coverage.xml

      src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  deploy:
  - provider: NuGet
    api_key:
      secure: UDzyB4rW2T34FpiDGyfUCSlSU0OljTZuIphVPbPxvm6RIElHiyZ021zOwKBNFn33
  notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    auth_token:
      secure: YQuy7rWA8Asj6RcjyKgF5g==
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

# Development CI
-
  branches:
    only:
      - development
  version: 0.1.{build}.0-beta
  os: Visual Studio 2015
  configuration: Debug
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    COVERALLS_REPO_TOKEN:
      secure: pJSh3uNVX95c4AMMnIWH6fy6EX8nywcfbgi2WqbuwYaWS6JQMHy6WFX0foQM4iHl
  before_build:
  - cmd: nuget restore src\Crankshaft.sln
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    project: src\Crankshaft.sln
    verbosity: minimal
  after_test:
  - cmd: >-
      src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe -targetargs:"src\En.Gen.Crankshaft.Tests\bin\debug\Crankshaft.Tests.dll -noshadow -appveyor" -filter:"+[Crankshaft*]* -[*.Tests]*" -output:coverage.xml

      src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  deploy:
  - provider: NuGet
    api_key:
      secure: UDzyB4rW2T34FpiDGyfUCSlSU0OljTZuIphVPbPxvm6RIElHiyZ021zOwKBNFn33
  notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    auth_token:
      secure: YQuy7rWA8Asj6RcjyKgF5g==
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

# Pull Requests - no nuget publish
-
  branches:
    except:
      - master
      - development
  version: 0.1.{build}.0-beta
  pull_requests:
    do_not_increment_build_number: true
  os: Visual Studio 2015
  configuration: Debug
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    COVERALLS_REPO_TOKEN:
      secure: pJSh3uNVX95c4AMMnIWH6fy6EX8nywcfbgi2WqbuwYaWS6JQMHy6WFX0foQM4iHl
  before_build:
  - cmd: nuget restore src\Crankshaft.sln
  build:
    project: src\Crankshaft.sln
    verbosity: minimal
  after_test:
  - cmd: >-
      src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe -targetargs:"src\En.Gen.Crankshaft.Tests\bin\debug\Crankshaft.Tests.dll -noshadow -appveyor" -filter:"+[Crankshaft*]* -[*.Tests]*" -output:coverage.xml

      src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    auth_token:
      secure: YQuy7rWA8Asj6RcjyKgF5g==
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true