version: 0.1.0.{build}
os: Visual Studio 2015
configuration: Debug
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: pJSh3uNVX95c4AMMnIWH6fy6EX8nywcfbgi2WqbuwYaWS6JQMHy6WFX0foQM4iHl
before_build:
- cmd: nuget restore src\Crankshaft.sln
build:
  project: src\Crankshaft.sln
  verbosity: minimal